In [278]:
import numpy as np
import pandas as pd

In [279]:
df = pd.read_csv("diabetes.csv")

In [280]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [281]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [282]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [283]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [284]:
X = scaler.fit_transform(X)

In [285]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [286]:
X.shape

(768, 8)

In [287]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [288]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [289]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [290]:
model.fit(X_train, y_train, batch_size=32, epochs=15, validation_data=(X_test, y_test))

Epoch 1/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6678 - loss: 0.6207 - val_accuracy: 0.7338 - val_loss: 0.6011
Epoch 2/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5675 - val_accuracy: 0.7338 - val_loss: 0.5684
Epoch 3/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7280 - loss: 0.5299 - val_accuracy: 0.7662 - val_loss: 0.5418
Epoch 4/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7492 - loss: 0.5045 - val_accuracy: 0.7857 - val_loss: 0.5229
Epoch 5/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4850 - val_accuracy: 0.7662 - val_loss: 0.5123
Epoch 6/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.4709 - val_accuracy: 0.7662 - val_loss: 0.5058
Epoch 7/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4589 - val_accuracy: 0.7662 - val_loss: 0.5054
Epoch 8/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4519 - val_accuracy: 0.7597 - val_loss: 0.5028
Epoch 9/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4461 - val_accuracy: 0.7662 - val_loss: 0.5051
Epoch 10/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4408 - val_accuracy: 0.7792 - val_loss: 0.5070
Epoch 11/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4372 - val_accuracy: 0.7597 - val_loss: 0.5084
Epoch 12/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4349 - val_accuracy: 0.7662 - val_loss: 0.5110
Epoch 13/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4314 - val_accuracy: 0.7662 - val_loss: 0.5108
Epoch 14/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4294 - val_accuracy: 0.7597 - val_loss: 0.5154
Epoch 15/15
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4264 - val_accuracy: 0.7662 - val_loss: 0.5148

In [291]:
# 1. How to select appropriate optimizer
# 2. Number of Neurons in a layer
# 3. How to select Number of layers
# 4. All in one model

In [292]:
# pip install -U keras-tuner

In [293]:
import kerastuner as kt

In [294]:
 def build_model(hp):

  model = Sequential()

  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta'])

  model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=["accuracy"])

  return model

In [295]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [296]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [297]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [298]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [299]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [300]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7557 - loss: 0.5239 - val_accuracy: 0.7273 - val_loss: 0.5440
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7476 - loss: 0.5065 - val_accuracy: 0.7338 - val_loss: 0.5352
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4959 - val_accuracy: 0.7338 - val_loss: 0.5251
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4868 - val_accuracy: 0.7468 - val_loss: 0.5190
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4794 - val_accuracy: 0.7597 - val_loss: 0.5130
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4734 - val_accuracy: 0.7597 - val_loss: 0.5085
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4683 - val_accuracy: 0.7727 - val_loss: 0.5047
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4647 - val_accuracy: 0.7662 - val_loss: 0.5047
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4613 - val_accuracy: 0.7662 - val_loss: 0.5047
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4586 - val_accuracy: 0.7662 - val_loss: 0.5034
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4560 - val_accuracy: 0.7597 - val_loss: 0.5024
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4537 - val_accuracy: 0.7662 - val_loss: 0.5022
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4513 - val_accuracy: 0.7597 - val_loss: 0.5025
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4494 - val_accuracy: 0.7597 - val_loss: 0.5032
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4474 - val_accuracy: 0.7597 - val_loss: 0.5026
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4462 - val_accuracy: 0.7532 - val_loss: 0.5045
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4448 - val_accuracy: 0.7532 - val_loss: 0.5054
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4438 - val_accuracy: 0.7532 - val_loss: 0.5060
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4429 - val_accuracy: 0.7532 - val_loss: 0.5070
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4415 - val_accuracy: 0.7532 - val_loss: 0.5080
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4408 - val_accuracy: 0.7532 - val_loss: 0.5089
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7834 - loss: 0.4394 - val_accuracy: 0.7532 - val_loss: 0.5084
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4384 - val_accuracy: 0.7468 - val_loss: 0.5091
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4379 - val_accuracy: 0.7532 - val_loss: 0.5101
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4367 - val_accuracy: 0.7597 - val_loss: 0.5109
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7834 - loss: 0.4359 - val_accuracy: 0.7597 - val_loss: 0.5109
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7818 - loss: 0.4350 - val_accuracy: 0.7532 - val_loss: 0.5129
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4343 - val_accuracy: 0.7532 - val_loss: 0.5144
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4334 - val_accuracy: 0.7532 - val_loss: 0.5148
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4331 - val_accuracy: 0.7597 - val_loss: 0.5156
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4326 - val_accuracy: 0.7597 - val_loss: 0.5163
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4317 - val_accuracy: 0.7532 - val_loss: 0.5182
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4310 - val_accuracy: 0.7597 - val_loss: 0.5192
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4299 - val_accuracy: 0.7532 - val_loss: 0.5195
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4297 - val_accuracy: 0.7532 - val_loss: 0.5200
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4290 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4281 - val_accuracy: 0.7532 - val_loss: 0.5217
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4279 - val_accuracy: 0.7532 - val_loss: 0.5226
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4269 - val_accuracy: 0.7597 - val_loss: 0.5223
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4264 - val_accuracy: 0.7597 - val_loss: 0.5224
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4260 - val_accuracy: 0.7597 - val_loss: 0.5228
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4258 - val_accuracy: 0.7597 - val_loss: 0.5230
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4252 - val_accuracy: 0.7597 - val_loss: 0.5243
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4248 - val_accuracy: 0.7597 - val_loss: 0.5262
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4241 - val_accuracy: 0.7597 - val_loss: 0.5268
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4238 - val_accuracy: 0.7597 - val_loss: 0.5274
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4230 - val_accuracy: 0.7597 - val_loss: 0.5281
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4227 - val_accuracy: 0.7597 - val_loss: 0.5300
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4220 - val_accuracy: 0.7532 - val_loss: 0.5294
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4214 - val_accuracy: 0.7532 - val_loss: 0.5311
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4210 - val_accuracy: 0.7532 - val_loss: 0.5316
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4205 - val_accuracy: 0.7532 - val_loss: 0.5297
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4203 - val_accuracy: 0.7532 - val_loss: 0.5312
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4197 - val_accuracy: 0.7532 - val_loss: 0.5325
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4190 - val_accuracy: 0.7532 - val_loss: 0.5327
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4186 - val_accuracy: 0.7532 - val_loss: 0.5318
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4182 - val_accuracy: 0.7532 - val_loss: 0.5323
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4181 - val_accuracy: 0.7532 - val_loss: 0.5320
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4175 - val_accuracy: 0.7532 - val_loss: 0.5320
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4173 - val_accuracy: 0.7532 - val_loss: 0.5333
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4162 - val_accuracy: 0.7532 - val_loss: 0.5336
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.4160 - val_accuracy: 0.7532 - val_loss: 0.5356
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4157 - val_accuracy: 0.7532 - val_loss: 0.5363
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4158 - val_accuracy: 0.7532 - val_loss: 0.5356
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4152 - val_accuracy: 0.7597 - val_loss: 0.5351
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4146 - val_accuracy: 0.7597 - val_loss: 0.5350
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4145 - val_accuracy: 0.7597 - val_loss: 0.5365
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4138 - val_accuracy: 0.7468 - val_loss: 0.5368
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4133 - val_accuracy: 0.7468 - val_loss: 0.5389
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4128 - val_accuracy: 0.7468 - val_loss: 0.5383
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4121 - val_accuracy: 0.7532 - val_loss: 0.5393
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4119 - val_accuracy: 0.7468 - val_loss: 0.5402
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4118 - val_accuracy: 0.7468 - val_loss: 0.5408
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4111 - val_accuracy: 0.7468 - val_loss: 0.5424
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4107 - val_accuracy: 0.7468 - val_loss: 0.5427
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4102 - val_accuracy: 0.7468 - val_loss: 0.5430
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4097 - val_accuracy: 0.7532 - val_loss: 0.5411
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4098 - val_accuracy: 0.7532 - val_loss: 0.5430
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4088 - val_accuracy: 0.7532 - val_loss: 0.5419
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4087 - val_accuracy: 0.7532 - val_loss: 0.5438
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4084 - val_accuracy: 0.7403 - val_loss: 0.5451
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4082 - val_accuracy: 0.7403 - val_loss: 0.5462
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4078 - val_accuracy: 0.7403 - val_loss: 0.5468
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4079 - val_accuracy: 0.7468 - val_loss: 0.5463
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4070 - val_accuracy: 0.7468 - val_loss: 0.5466
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4070 - val_accuracy: 0.7468 - val_loss: 0.5481
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4061 - val_accuracy: 0.7468 - val_loss: 0.5483
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4055 - val_accuracy: 0.7468 - val_loss: 0.5493
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4059 - val_accuracy: 0.7532 - val_loss: 0.5480
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4054 - val_accuracy: 0.7403 - val_loss: 0.5490
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.4047 - val_accuracy: 0.7403 - val_loss: 0.5486
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4044 - val_accuracy: 0.7273 - val_loss: 0.5478
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4041 - val_accuracy: 0.7273 - val_loss: 0.5488
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4038 - val_accuracy: 0.7403 - val_loss: 0.5492

In [301]:
def build_model(hp):

  model = Sequential()

  units = hp.Int('units', min_value=8, max_value=128, step=8)

  model.add(Dense(units=units, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [302]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='Mandar Bavdane')

Reloading Tuner from mydir/Mandar Bavdane/tuner0.json

In [303]:
tuner.search(X_train, y_train, epochs=4, validation_data=(X_test, y_test))

In [304]:
tuner.get_best_hyperparameters()[0].values

{'units': 88}

In [305]:
model = tuner.get_best_models(num_models=1)[0]

In [306]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7671 - loss: 0.4898 - val_accuracy: 0.7792 - val_loss: 0.5019
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4745 - val_accuracy: 0.7857 - val_loss: 0.4997
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4670 - val_accuracy: 0.7792 - val_loss: 0.5000
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4610 - val_accuracy: 0.7792 - val_loss: 0.5022
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4561 - val_accuracy: 0.7792 - val_loss: 0.5025
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4522 - val_accuracy: 0.7727 - val_loss: 0.5026
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4499 - val_accuracy: 0.7727 - val_loss: 0.5047
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4473 - val_accuracy: 0.7727 - val_loss: 0.5064
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4445 - val_accuracy: 0.7662 - val_loss: 0.5068
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4418 - val_accuracy: 0.7662 - val_loss: 0.5088
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4405 - val_accuracy: 0.7597 - val_loss: 0.5130
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4370 - val_accuracy: 0.7662 - val_loss: 0.5132
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4356 - val_accuracy: 0.7662 - val_loss: 0.5170
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4336 - val_accuracy: 0.7597 - val_loss: 0.5220
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4324 - val_accuracy: 0.7597 - val_loss: 0.5225
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4313 - val_accuracy: 0.7532 - val_loss: 0.5236
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4291 - val_accuracy: 0.7662 - val_loss: 0.5240
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4272 - val_accuracy: 0.7597 - val_loss: 0.5253
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4260 - val_accuracy: 0.7597 - val_loss: 0.5287
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4253 - val_accuracy: 0.7597 - val_loss: 0.5290
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4240 - val_accuracy: 0.7532 - val_loss: 0.5304
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4222 - val_accuracy: 0.7662 - val_loss: 0.5308
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4211 - val_accuracy: 0.7597 - val_loss: 0.5316
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4197 - val_accuracy: 0.7597 - val_loss: 0.5331
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4189 - val_accuracy: 0.7597 - val_loss: 0.5294
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4178 - val_accuracy: 0.7597 - val_loss: 0.5300
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4167 - val_accuracy: 0.7597 - val_loss: 0.5315
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4155 - val_accuracy: 0.7727 - val_loss: 0.5326
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4145 - val_accuracy: 0.7597 - val_loss: 0.5341
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4137 - val_accuracy: 0.7662 - val_loss: 0.5328
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7997 - loss: 0.4125 - val_accuracy: 0.7662 - val_loss: 0.5316
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7997 - loss: 0.4128 - val_accuracy: 0.7727 - val_loss: 0.5322
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4104 - val_accuracy: 0.7597 - val_loss: 0.5367
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4109 - val_accuracy: 0.7532 - val_loss: 0.5396
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4096 - val_accuracy: 0.7532 - val_loss: 0.5388
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4088 - val_accuracy: 0.7597 - val_loss: 0.5385
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4081 - val_accuracy: 0.7597 - val_loss: 0.5385
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4073 - val_accuracy: 0.7597 - val_loss: 0.5409
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4057 - val_accuracy: 0.7532 - val_loss: 0.5448
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4055 - val_accuracy: 0.7597 - val_loss: 0.5415
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4044 - val_accuracy: 0.7597 - val_loss: 0.5412
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4048 - val_accuracy: 0.7597 - val_loss: 0.5420
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4030 - val_accuracy: 0.7597 - val_loss: 0.5434
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4027 - val_accuracy: 0.7597 - val_loss: 0.5427
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4015 - val_accuracy: 0.7597 - val_loss: 0.5440
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4017 - val_accuracy: 0.7597 - val_loss: 0.5453
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4002 - val_accuracy: 0.7597 - val_loss: 0.5478
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3999 - val_accuracy: 0.7597 - val_loss: 0.5472
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3998 - val_accuracy: 0.7597 - val_loss: 0.5479
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3984 - val_accuracy: 0.7662 - val_loss: 0.5464
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3983 - val_accuracy: 0.7597 - val_loss: 0.5480
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3977 - val_accuracy: 0.7597 - val_loss: 0.5458
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3966 - val_accuracy: 0.7597 - val_loss: 0.5461
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3962 - val_accuracy: 0.7662 - val_loss: 0.5476
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3960 - val_accuracy: 0.7597 - val_loss: 0.5481
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3955 - val_accuracy: 0.7597 - val_loss: 0.5496
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3948 - val_accuracy: 0.7662 - val_loss: 0.5512
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3933 - val_accuracy: 0.7597 - val_loss: 0.5528
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3940 - val_accuracy: 0.7532 - val_loss: 0.5497
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3927 - val_accuracy: 0.7532 - val_loss: 0.5532
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3926 - val_accuracy: 0.7532 - val_loss: 0.5534
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3926 - val_accuracy: 0.7597 - val_loss: 0.5535
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3917 - val_accuracy: 0.7532 - val_loss: 0.5509
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.3914 - val_accuracy: 0.7468 - val_loss: 0.5501
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3902 - val_accuracy: 0.7532 - val_loss: 0.5532
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8192 - loss: 0.3900 - val_accuracy: 0.7597 - val_loss: 0.5540
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8225 - loss: 0.3896 - val_accuracy: 0.7468 - val_loss: 0.5512
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.3885 - val_accuracy: 0.7597 - val_loss: 0.5523
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8241 - loss: 0.3888 - val_accuracy: 0.7597 - val_loss: 0.5528
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3888 - val_accuracy: 0.7597 - val_loss: 0.5540
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8274 - loss: 0.3876 - val_accuracy: 0.7597 - val_loss: 0.5540
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8257 - loss: 0.3871 - val_accuracy: 0.7532 - val_loss: 0.5546
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8241 - loss: 0.3869 - val_accuracy: 0.7532 - val_loss: 0.5539
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8257 - loss: 0.3860 - val_accuracy: 0.7532 - val_loss: 0.5578
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8290 - loss: 0.3855 - val_accuracy: 0.7532 - val_loss: 0.5565
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8225 - loss: 0.3851 - val_accuracy: 0.7597 - val_loss: 0.5557
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8241 - loss: 0.3840 - val_accuracy: 0.7597 - val_loss: 0.5555
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3844 - val_accuracy: 0.7468 - val_loss: 0.5581
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3837 - val_accuracy: 0.7532 - val_loss: 0.5581
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3838 - val_accuracy: 0.7532 - val_loss: 0.5606
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3825 - val_accuracy: 0.7597 - val_loss: 0.5630
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.3830 - val_accuracy: 0.7597 - val_loss: 0.5642
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3822 - val_accuracy: 0.7597 - val_loss: 0.5670
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3817 - val_accuracy: 0.7597 - val_loss: 0.5655
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3811 - val_accuracy: 0.7597 - val_loss: 0.5622
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3805 - val_accuracy: 0.7597 - val_loss: 0.5655
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3797 - val_accuracy: 0.7597 - val_loss: 0.5642
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3799 - val_accuracy: 0.7597 - val_loss: 0.5666
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3794 - val_accuracy: 0.7597 - val_loss: 0.5698
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8322 - loss: 0.3788 - val_accuracy: 0.7597 - val_loss: 0.5701
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3783 - val_accuracy: 0.7468 - val_loss: 0.5639
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3781 - val_accuracy: 0.7597 - val_loss: 0.5635
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3777 - val_accuracy: 0.7532 - val_loss: 0.5646
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3775 - val_accuracy: 0.7597 - val_loss: 0.5650

#How to Select Number of Layers

In [307]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(72, activation='relu', input_dim=8))

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

  return model

In [308]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=3,
                        directory='mydir',
                        project_name='num_layers')

Reloading Tuner from mydir/num_layers/tuner0.json

In [309]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [310]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 1}

In [311]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [312]:
model.fit(X_train, y_train, batch_size=32, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - accuracy: 0.7736 - loss: 0.4641 - val_accuracy: 0.7532 - val_loss: 0.5056
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4511 - val_accuracy: 0.7662 - val_loss: 0.5095
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4436 - val_accuracy: 0.7662 - val_loss: 0.5116
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7915 - loss: 0.4374 - val_accuracy: 0.7468 - val_loss: 0.5205
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4340 - val_accuracy: 0.7662 - val_loss: 0.5195
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4306 - val_accuracy: 0.7597 - val_loss: 0.5185
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4262 - val_accuracy: 0.7662 - val_loss: 0.5237
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4207 - val_accuracy: 0.7662 - val_loss: 0.5264
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4204 - val_accuracy: 0.7597 - val_loss: 0.5345
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4157 - val_accuracy: 0.7338 - val_loss: 0.5438
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4150 - val_accuracy: 0.7532 - val_loss: 0.5410
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4107 - val_accuracy: 0.7468 - val_loss: 0.5485
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4098 - val_accuracy: 0.7532 - val_loss: 0.5468
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4065 - val_accuracy: 0.7597 - val_loss: 0.5500
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4045 - val_accuracy: 0.7597 - val_loss: 0.5468
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.4012 - val_accuracy: 0.7532 - val_loss: 0.5427
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.3991 - val_accuracy: 0.7468 - val_loss: 0.5511
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.3946 - val_accuracy: 0.7532 - val_loss: 0.5571
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3941 - val_accuracy: 0.7532 - val_loss: 0.5480
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.3922 - val_accuracy: 0.7338 - val_loss: 0.5621
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3897 - val_accuracy: 0.7403 - val_loss: 0.5629
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3893 - val_accuracy: 0.7532 - val_loss: 0.5678
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8339 - loss: 0.3854 - val_accuracy: 0.7532 - val_loss: 0.5619
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3842 - val_accuracy: 0.7532 - val_loss: 0.5575
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3813 - val_accuracy: 0.7532 - val_loss: 0.5827
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3786 - val_accuracy: 0.7143 - val_loss: 0.5834
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3796 - val_accuracy: 0.7532 - val_loss: 0.5638
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3767 - val_accuracy: 0.7468 - val_loss: 0.5745
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8274 - loss: 0.3746 - val_accuracy: 0.7273 - val_loss: 0.5821
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3729 - val_accuracy: 0.7338 - val_loss: 0.5834
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8274 - loss: 0.3693 - val_accuracy: 0.7143 - val_loss: 0.5898
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8339 - loss: 0.3689 - val_accuracy: 0.7532 - val_loss: 0.5693
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8453 - loss: 0.3656 - val_accuracy: 0.7532 - val_loss: 0.5728
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8322 - loss: 0.3611 - val_accuracy: 0.7597 - val_loss: 0.5944
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8306 - loss: 0.3651 - val_accuracy: 0.7468 - val_loss: 0.5648
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8371 - loss: 0.3602 - val_accuracy: 0.7532 - val_loss: 0.5778
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8339 - loss: 0.3593 - val_accuracy: 0.7338 - val_loss: 0.5919
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8469 - loss: 0.3573 - val_accuracy: 0.7338 - val_loss: 0.5976
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3540 - val_accuracy: 0.7597 - val_loss: 0.5868
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3552 - val_accuracy: 0.7468 - val_loss: 0.5854
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3542 - val_accuracy: 0.7532 - val_loss: 0.5836
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3517 - val_accuracy: 0.7468 - val_loss: 0.5927
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3478 - val_accuracy: 0.7403 - val_loss: 0.6022
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3461 - val_accuracy: 0.7597 - val_loss: 0.5942
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3432 - val_accuracy: 0.7468 - val_loss: 0.5904
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8502 - loss: 0.3431 - val_accuracy: 0.7403 - val_loss: 0.5960
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3430 - val_accuracy: 0.7403 - val_loss: 0.6069
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3391 - val_accuracy: 0.7468 - val_loss: 0.5992
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3348 - val_accuracy: 0.7403 - val_loss: 0.6216
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3374 - val_accuracy: 0.7727 - val_loss: 0.6123
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3343 - val_accuracy: 0.7468 - val_loss: 0.6180
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3322 - val_accuracy: 0.7532 - val_loss: 0.5988
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3289 - val_accuracy: 0.7143 - val_loss: 0.6247
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3268 - val_accuracy: 0.7468 - val_loss: 0.6234
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3249 - val_accuracy: 0.7143 - val_loss: 0.6252
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8567 - loss: 0.3243 - val_accuracy: 0.7468 - val_loss: 0.6244
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3227 - val_accuracy: 0.7338 - val_loss: 0.6362
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3208 - val_accuracy: 0.7338 - val_loss: 0.6400
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8599 - loss: 0.3192 - val_accuracy: 0.7273 - val_loss: 0.6361
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3174 - val_accuracy: 0.7338 - val_loss: 0.6179
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3131 - val_accuracy: 0.7208 - val_loss: 0.6348
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8583 - loss: 0.3114 - val_accuracy: 0.7403 - val_loss: 0.6311
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3096 - val_accuracy: 0.7403 - val_loss: 0.6412
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3099 - val_accuracy: 0.7208 - val_loss: 0.6475
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3067 - val_accuracy: 0.7273 - val_loss: 0.6351
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3050 - val_accuracy: 0.7468 - val_loss: 0.6344
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3058 - val_accuracy: 0.7403 - val_loss: 0.6399
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3012 - val_accuracy: 0.7208 - val_loss: 0.6477
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8664 - loss: 0.2982 - val_accuracy: 0.7273 - val_loss: 0.6648
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8616 - loss: 0.2944 - val_accuracy: 0.7597 - val_loss: 0.6611
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.2932 - val_accuracy: 0.7078 - val_loss: 0.6931
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.2948 - val_accuracy: 0.7208 - val_loss: 0.6729
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2912 - val_accuracy: 0.7662 - val_loss: 0.6599
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.2891 - val_accuracy: 0.7403 - val_loss: 0.6652
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.2893 - val_accuracy: 0.7597 - val_loss: 0.6647
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.2885 - val_accuracy: 0.7208 - val_loss: 0.6859
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8746 - loss: 0.2849 - val_accuracy: 0.7468 - val_loss: 0.6551
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8681 - loss: 0.2839 - val_accuracy: 0.7273 - val_loss: 0.6839
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.2798 - val_accuracy: 0.7338 - val_loss: 0.6990
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.2784 - val_accuracy: 0.7143 - val_loss: 0.7196
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2775 - val_accuracy: 0.7403 - val_loss: 0.6914
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2725 - val_accuracy: 0.7597 - val_loss: 0.6701
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2715 - val_accuracy: 0.7208 - val_loss: 0.6995
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8730 - loss: 0.2699 - val_accuracy: 0.7532 - val_loss: 0.7023
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8876 - loss: 0.2688 - val_accuracy: 0.7143 - val_loss: 0.7279
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.2675 - val_accuracy: 0.7597 - val_loss: 0.6801
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8713 - loss: 0.2657 - val_accuracy: 0.7662 - val_loss: 0.6841
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8925 - loss: 0.2623 - val_accuracy: 0.7532 - val_loss: 0.7011
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2613 - val_accuracy: 0.7468 - val_loss: 0.7065
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8860 - loss: 0.2559 - val_accuracy: 0.7208 - val_loss: 0.7281
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2589 - val_accuracy: 0.7468 - val_loss: 0.7250
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2545 - val_accuracy: 0.7273 - val_loss: 0.7193
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8844 - loss: 0.2520 - val_accuracy: 0.7532 - val_loss: 0.7102
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2517 - val_accuracy: 0.7273 - val_loss: 0.7180

In [313]:
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):

    if counter == 0:

      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8), activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])))
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))


    else:

      model.add(Dense(hp.Int('units' + str(i), min_value=8, max_value=128, step=8), activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])))
      model.add(Dropout(hp.Choice('dropout' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))

    counter += 1

  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop', 'adadelta', 'nadam']),
                loss='binary_crossentropy',
                metrics=['accuracy']
                )

  return model

In [314]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='Full&Final')

In [315]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.7142857313156128
Total elapsed time: 00h 00m 27s

In [316]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 104,
 'activation0': 'tanh',
 'dropout0': 0.1,
 'optimizer': 'sgd',
 'units1': 96,
 'activation1': 'sigmoid',
 'dropout1': 0.2,
 'units2': 32,
 'activation2': 'sigmoid',
 'dropout2': 0.8,
 'units3': 8,
 'activation3': 'tanh',
 'dropout3': 0.2,
 'units4': 32,
 'activation4': 'tanh',
 'dropout4': 0.4,
 'units5': 56,
 'activation5': 'tanh',
 'dropout5': 0.6,
 'units6': 112,
 'activation6': 'tanh',
 'dropout6': 0.5,
 'units7': 16,
 'activation7': 'tanh',
 'dropout7': 0.5,
 'units8': 8,
 'activation8': 'sigmoid',
 'dropout8': 0.5,
 'units9': 24,
 'activation9': 'sigmoid',
 'dropout9': 0.7}

In [317]:
model = tuner.get_best_models(num_models=1)[0]

In [277]:
model.fit(X_train, y_train, epochs=200, initial_epoch=5, validation_data=(X_test, y_test))

Epoch 6/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.7296 - loss: 0.5229 - val_accuracy: 0.7468 - val_loss: 0.5282
Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7329 - loss: 0.5013 - val_accuracy: 0.7143 - val_loss: 0.5298
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4927 - val_accuracy: 0.7013 - val_loss: 0.5260
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4826 - val_accuracy: 0.7597 - val_loss: 0.5070
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4734 - val_accuracy: 0.7662 - val_loss: 0.5025
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4678 - val_accuracy: 0.7468 - val_loss: 0.5010
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4625 - val_accuracy: 0.7208 - val_loss: 0.5114
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4547 - val_accuracy: 0.7597 - val_loss: 0.5036
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4571 - val_accuracy: 0.7403 - val_loss: 0.5101
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4540 - val_accuracy: 0.7468 - val_loss: 0.5054
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4520 - val_accuracy: 0.7208 - val_loss: 0.5175
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4453 - val_accuracy: 0.7662 - val_loss: 0.5054
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4486 - val_accuracy: 0.7338 - val_loss: 0.5179
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.7687 - loss: 0.4487 - val_accuracy: 0.7338 - val_loss: 0.5153
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.7736 - loss: 0.4430 - val_accuracy: 0.7922 - val_loss: 0.5077
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7818 - loss: 0.4444 - val_accuracy: 0.7338 - val_loss: 0.5272
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4389 - val_accuracy: 0.7597 - val_loss: 0.5102
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7866 - loss: 0.4401 - val_accuracy: 0.7078 - val_loss: 0.5334
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.7834 - loss: 0.4392 - val_accuracy: 0.7857 - val_loss: 0.5164
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.7818 - loss: 0.4399 - val_accuracy: 0.7857 - val_loss: 0.5135
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7866 - loss: 0.4372 - val_accuracy: 0.7792 - val_loss: 0.5162
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4371 - val_accuracy: 0.7662 - val_loss: 0.5160
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4345 - val_accuracy: 0.7338 - val_loss: 0.5327
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4332 - val_accuracy: 0.7662 - val_loss: 0.5198
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4351 - val_accuracy: 0.7597 - val_loss: 0.5220
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4309 - val_accuracy: 0.7597 - val_loss: 0.5240
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4301 - val_accuracy: 0.7208 - val_loss: 0.5333
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4299 - val_accuracy: 0.7597 - val_loss: 0.5293
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4332 - val_accuracy: 0.7597 - val_loss: 0.5284
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4290 - val_accuracy: 0.7662 - val_loss: 0.5263
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4273 - val_accuracy: 0.7597 - val_loss: 0.5298
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4290 - val_accuracy: 0.7727 - val_loss: 0.5280
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4252 - val_accuracy: 0.7208 - val_loss: 0.5493
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4244 - val_accuracy: 0.7597 - val_loss: 0.5286
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4240 - val_accuracy: 0.7727 - val_loss: 0.5280
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4266 - val_accuracy: 0.7597 - val_loss: 0.5299
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4216 - val_accuracy: 0.7273 - val_loss: 0.5387
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4224 - val_accuracy: 0.7597 - val_loss: 0.5306
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7899 - loss: 0.4231 - val_accuracy: 0.7597 - val_loss: 0.5356
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4193 - val_accuracy: 0.7727 - val_loss: 0.5339
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4194 - val_accuracy: 0.7532 - val_loss: 0.5396
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8013 - loss: 0.4184 - val_accuracy: 0.7468 - val_loss: 0.5376
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7948 - loss: 0.4152 - val_accuracy: 0.7273 - val_loss: 0.5430
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4182 - val_accuracy: 0.7597 - val_loss: 0.5402
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4168 - val_accuracy: 0.7013 - val_loss: 0.5574
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4175 - val_accuracy: 0.7208 - val_loss: 0.5495
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7948 - loss: 0.4175 - val_accuracy: 0.7727 - val_loss: 0.5364
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7980 - loss: 0.4100 - val_accuracy: 0.7727 - val_loss: 0.5363
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4128 - val_accuracy: 0.7208 - val_loss: 0.5485
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4132 - val_accuracy: 0.7532 - val_loss: 0.5435
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4161 - val_accuracy: 0.7143 - val_loss: 0.5636
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4125 - val_accuracy: 0.7273 - val_loss: 0.5539
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4135 - val_accuracy: 0.7468 - val_loss: 0.5478
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4137 - val_accuracy: 0.7727 - val_loss: 0.5436
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4087 - val_accuracy: 0.7532 - val_loss: 0.5470
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4098 - val_accuracy: 0.7727 - val_loss: 0.5491
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4132 - val_accuracy: 0.7468 - val_loss: 0.5536
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4121 - val_accuracy: 0.7468 - val_loss: 0.5545
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4079 - val_accuracy: 0.7468 - val_loss: 0.5541
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4071 - val_accuracy: 0.7662 - val_loss: 0.5509
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4071 - val_accuracy: 0.7468 - val_loss: 0.5606
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4078 - val_accuracy: 0.7727 - val_loss: 0.5535
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4082 - val_accuracy: 0.7662 - val_loss: 0.5531
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4036 - val_accuracy: 0.7857 - val_loss: 0.5573
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4077 - val_accuracy: 0.7597 - val_loss: 0.5573
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4028 - val_accuracy: 0.7403 - val_loss: 0.5644
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4047 - val_accuracy: 0.7727 - val_loss: 0.5538
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4051 - val_accuracy: 0.7727 - val_loss: 0.5527
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4004 - val_accuracy: 0.7338 - val_loss: 0.5663
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4013 - val_accuracy: 0.7727 - val_loss: 0.5553
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.3961 - val_accuracy: 0.6883 - val_loss: 0.6017
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4004 - val_accuracy: 0.7208 - val_loss: 0.5620
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4003 - val_accuracy: 0.7532 - val_loss: 0.5569
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3986 - val_accuracy: 0.7143 - val_loss: 0.5708
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4031 - val_accuracy: 0.7468 - val_loss: 0.5550
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3960 - val_accuracy: 0.6688 - val_loss: 0.6001
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3993 - val_accuracy: 0.7727 - val_loss: 0.5489
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3989 - val_accuracy: 0.7857 - val_loss: 0.5487
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.3952 - val_accuracy: 0.7013 - val_loss: 0.5718
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3974 - val_accuracy: 0.7273 - val_loss: 0.5640
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.3964 - val_accuracy: 0.7468 - val_loss: 0.5625
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3967 - val_accuracy: 0.7403 - val_loss: 0.5678
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3973 - val_accuracy: 0.7403 - val_loss: 0.5670
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3941 - val_accuracy: 0.7727 - val_loss: 0.5599
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.3890 - val_accuracy: 0.7078 - val_loss: 0.5913
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3947 - val_accuracy: 0.7792 - val_loss: 0.5602
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3909 - val_accuracy: 0.7727 - val_loss: 0.5624
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3929 - val_accuracy: 0.7532 - val_loss: 0.5693
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3897 - val_accuracy: 0.7338 - val_loss: 0.5789
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3892 - val_accuracy: 0.7792 - val_loss: 0.5667
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3885 - val_accuracy: 0.7403 - val_loss: 0.5703
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3907 - val_accuracy: 0.6948 - val_loss: 0.6017
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3910 - val_accuracy: 0.7597 - val_loss: 0.5707
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3857 - val_accuracy: 0.7727 - val_loss: 0.5716
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8225 - loss: 0.3882 - val_accuracy: 0.7727 - val_loss: 0.5655
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3888 - val_accuracy: 0.7922 - val_loss: 0.5657
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3880 - val_accuracy: 0.7727 - val_loss: 0.5667
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3868 - val_accuracy: 0.7078 - val_loss: 0.5926
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3877 - val_accuracy: 0.7143 - val_loss: 0.5883
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3845 - val_accuracy: 0.7143 - val_loss: 0.5933
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3836 - val_accuracy: 0.7532 - val_loss: 0.5769
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3823 - val_accuracy: 0.7727 - val_loss: 0.5660
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3824 - val_accuracy: 0.7208 - val_loss: 0.5980
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8143 - loss: 0.3836 - val_accuracy: 0.6883 - val_loss: 0.6083
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3860 - val_accuracy: 0.7143 - val_loss: 0.5881
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3827 - val_accuracy: 0.7727 - val_loss: 0.5727
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3817 - val_accuracy: 0.7922 - val_loss: 0.5771
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3805 - val_accuracy: 0.7727 - val_loss: 0.5701
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3788 - val_accuracy: 0.7662 - val_loss: 0.5745
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3787 - val_accuracy: 0.7727 - val_loss: 0.5813
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3782 - val_accuracy: 0.7013 - val_loss: 0.6086
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3787 - val_accuracy: 0.7338 - val_loss: 0.5835
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8306 - loss: 0.3775 - val_accuracy: 0.7013 - val_loss: 0.6113
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.8225 - loss: 0.3785 - val_accuracy: 0.7857 - val_loss: 0.5790
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - accuracy: 0.8176 - loss: 0.3810 - val_accuracy: 0.7143 - val_loss: 0.6048
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.8322 - loss: 0.3753 - val_accuracy: 0.7273 - val_loss: 0.5901
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.8257 - loss: 0.3772 - val_accuracy: 0.7532 - val_loss: 0.5776
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8257 - loss: 0.3759 - val_accuracy: 0.7597 - val_loss: 0.5773
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8192 - loss: 0.3742 - val_accuracy: 0.7403 - val_loss: 0.5873
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8306 - loss: 0.3723 - val_accuracy: 0.7208 - val_loss: 0.5850
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8225 - loss: 0.3755 - val_accuracy: 0.6883 - val_loss: 0.6138
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8225 - loss: 0.3753 - val_accuracy: 0.7078 - val_loss: 0.6061
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3716 - val_accuracy: 0.6883 - val_loss: 0.6157
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3734 - val_accuracy: 0.7597 - val_loss: 0.5896
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3700 - val_accuracy: 0.7078 - val_loss: 0.6092
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3697 - val_accuracy: 0.7532 - val_loss: 0.5866
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8241 - loss: 0.3722 - val_accuracy: 0.7208 - val_loss: 0.5913
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3696 - val_accuracy: 0.7468 - val_loss: 0.5845
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3684 - val_accuracy: 0.7727 - val_loss: 0.5864
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3689 - val_accuracy: 0.7662 - val_loss: 0.5861
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3712 - val_accuracy: 0.7597 - val_loss: 0.5887
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3681 - val_accuracy: 0.7662 - val_loss: 0.5852
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3667 - val_accuracy: 0.7727 - val_loss: 0.5807
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3657 - val_accuracy: 0.7338 - val_loss: 0.5949
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3648 - val_accuracy: 0.7208 - val_loss: 0.6069
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3627 - val_accuracy: 0.7338 - val_loss: 0.5930
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3625 - val_accuracy: 0.7597 - val_loss: 0.5882
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3635 - val_accuracy: 0.7208 - val_loss: 0.5969
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3607 - val_accuracy: 0.7338 - val_loss: 0.5963
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3606 - val_accuracy: 0.7273 - val_loss: 0.5984
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3586 - val_accuracy: 0.7468 - val_loss: 0.6018
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3615 - val_accuracy: 0.6883 - val_loss: 0.6416
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3620 - val_accuracy: 0.7338 - val_loss: 0.6029
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3559 - val_accuracy: 0.7468 - val_loss: 0.5981
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3591 - val_accuracy: 0.7468 - val_loss: 0.6054
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3570 - val_accuracy: 0.7532 - val_loss: 0.6038
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3578 - val_accuracy: 0.7078 - val_loss: 0.6257
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3529 - val_accuracy: 0.7143 - val_loss: 0.6159
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3556 - val_accuracy: 0.7143 - val_loss: 0.6136
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3528 - val_accuracy: 0.7597 - val_loss: 0.6025
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3513 - val_accuracy: 0.7468 - val_loss: 0.6043
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8453 - loss: 0.3470 - val_accuracy: 0.6948 - val_loss: 0.6486
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3485 - val_accuracy: 0.7532 - val_loss: 0.5994
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3498 - val_accuracy: 0.7143 - val_loss: 0.6120
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3450 - val_accuracy: 0.7143 - val_loss: 0.6186
Epoch 161/200